services:
    Triggerfish_doctrine_encrypt.orm_subscriber:
        class: Triggerfish\DoctrineEncryptBundle\Subscribers\DoctrineEncryptSubscriber
        arguments: ["@annotation_reader", "%Triggerfish_doctrine_encrypt.encryptor_class_name%", "%Triggerfish_doctrine_encrypt.secret_key%"]
        tags:
            -  { name: doctrine.event_subscriber }
    Triggerfish_doctrine_encrypt.subscriber:
        alias: Triggerfish_doctrine_encrypt.orm_subscriber
    Triggerfish_doctrine_encrypt.encryptor:
        class: Triggerfish\DoctrineEncryptBundle\Services\Encryptor
        arguments:
            - "%Triggerfish_doctrine_encrypt.encryptor_class_name%"
            - "%Triggerfish_doctrine_encrypt.secret_key%"
